import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import NavbarComponent from "@/app/components/ui/Navbar";
import SideMenu from "@/app/components/ui/SideMenu";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Providers>
          <>
            <div className="border-b">
              <NavbarComponent />
            </div>
            <div className="container mx-auto px-5 py-5">
              <div className="flex">
                <SideMenu />
                {children}
              </div>
            </div>
          </>
        </Providers>
      </body>
    </html>
  )
}
